const POS_KEY='xiuxian-game-fab-position', LAST_SLOT_KEY='xiuxian-game-last-slot';
const DB_NAME='xiuxian-game'; const DB_VERSION=1; const SLOTS=['slot1','slot2','slot3','slot4','slot5'];
let currentSave=null,currentSlot=null;
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('saves'))d.createObjectStore('saves',{keyPath:'slot'});if(!d.objectStoreNames.contains('assets'))d.createObjectStore('assets',{keyPath:'id'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function dbRequest(mode,operation){
 const d=await openDB();
 return new Promise((ok,no)=>{
  let tx,result,request;
  try{tx=d.transaction('saves',mode);request=operation(tx.objectStore('saves'))}
  catch(error){d.close();no(error);return}
  request.onsuccess=()=>{result=request.result};
  tx.oncomplete=()=>{d.close();ok(result)};
  tx.onabort=()=>{d.close();no(tx.error||request.error||new Error('存档事务已中止'))};
  tx.onerror=()=>{}; // Transaction errors abort by default; reject from onabort.
 })
}
async function dbGet(slot){return (await dbRequest('readonly',store=>store.get(slot)))||null}
async function dbPut(data){await dbRequest('readwrite',store=>store.put(data));return data}
async function dbDelete(slot){await dbRequest('readwrite',store=>store.delete(slot))}
async function runAction(action){try{return await action()}catch(error){console.error('[xiuxian-game]',error);alert('操作未完成，请重试。存档读取或写入失败。')}}
function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function clampFabPosition(left,top,width,height,viewportWidth,viewportHeight){return{left:Math.max(4,Math.min(viewportWidth-width-4,Number.isFinite(left)?left:viewportWidth-width-8)),top:Math.max(4,Math.min(viewportHeight-height-4,Number.isFinite(top)?top:viewportHeight/2-height/2))}}
const NAV_ICONS={
 home:'<path d="M3 11 12 3l9 8M5 10v11h14V10M9 21v-7h6v7"/>',
 person:'<circle cx="12" cy="7" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 bag:'<path d="M8 3h8l-2 5c5 3 7 6 7 9a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4c0-3 2-6 7-9L8 3ZM9 8h6M9 12h6"/>',
 map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5ZM9 3v16M15 5v16"/>',
 settings:'<path d="M5 3v18M12 3v18M19 3v18M2 8h6M9 16h6M16 8h6"/>'
};
function navButton(icon,label,id='',active=false){return `<button type="button"${id?` id="${id}"`:''}${active?' class="on"':''} aria-label="${label}"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">${NAV_ICONS[icon]}</svg><small>${label}</small></button>`}
const elements=['金','木','水','火','土'];
const roots=[];
const rootBonus={
  variant:{悟性:0,根骨:1,福缘:2,神识:0,魅力:1},
  single:{悟性:0,根骨:1,福缘:1,神识:0,魅力:1},
  double:{悟性:1,根骨:1,福缘:0,神识:1,魅力:0},
  triple:{悟性:2,根骨:1,福缘:0,神识:0,魅力:0},
  quad:{悟性:1,根骨:2,福缘:0,神识:0,魅力:0},
  five:{悟性:1,根骨:1,福缘:0,神识:1,魅力:-1}
};
function addRoot(name,type){roots.push({name,type,bonus:rootBonus[type]})}
['雷灵根','冰灵根','风灵根'].forEach(n=>addRoot(n,'variant'));
elements.forEach(e=>addRoot(e+'灵根','single'));
for(let i=0;i<elements.length;i++)for(let k=i+1;k<elements.length;k++)addRoot(elements[i]+elements[k]+'双灵根','double');
for(let i=0;i<elements.length;i++)for(let k=i+1;k<elements.length;k++)for(let m=k+1;m<elements.length;m++)addRoot(elements[i]+elements[k]+elements[m]+'三灵根','triple');
for(let omit=0;omit<elements.length;omit++)addRoot(elements.filter((_,i)=>i!==omit).join('')+'四灵根','quad');
addRoot('金木水火土五灵根','five');
function pickRoot(){return roots[Math.floor(Math.random()*roots.length)]}
const STAT_NAMES=['悟性','根骨','福缘','神识','魅力'], FREE_POINTS=30, STAT_CAP=10;
function emptyAllocation(){return{悟性:0,根骨:0,福缘:0,神识:0,魅力:0}}
function finalStats(root,alloc){const out={};for(const k of STAT_NAMES)out[k]=(alloc[k]||0)+(root.bonus[k]||0);return out}
function rootDesc(root){const b=STAT_NAMES.filter(k=>root.bonus[k]).map(k=>k+(root.bonus[k]>0?'+':'')+root.bonus[k]).join(' · ');return root.name+'｜'+b}
function newSave(name,gender,root,alloc){const stats=finalStats(root,alloc);return{slot:currentSlot,version:3,createdAt:Date.now(),updatedAt:Date.now(),player:{name,gender,realm:'炼气一层',sect:'无门无派',cultivation:0,spirit:100,hp:100,mind:60,spiritRoot:root.name,rootType:root.type,rootDesc:rootDesc(root),aptitude:root.bonus,stats},story:{chapter:1,revenge:true,homeDestroyed:true},inventory:[],events:[],flags:{}}}
async function saveNow(){if(!currentSave||!currentSlot)return;currentSave.slot=currentSlot;currentSave.updatedAt=Date.now();await dbPut(currentSave)}
function renderHome(){const p=currentSave.player;document.getElementById('xg-content').innerHTML=`<div class="xg-card xg-player"><div><strong>${escapeHTML(p.name)}</strong><small>${escapeHTML(p.gender||'未设')} · ${escapeHTML(p.sect)}</small></div><em>${escapeHTML(p.realm)}</em></div><div class="xg-card"><h3>⌖ 荒山古道</h3><p>故山已成焦土。你将旧门残玉收在怀中，自此踏上修行路。<br>仇人的名字尚未从世间消失，你也不会。</p></div><div class="xg-card xg-stats"><h3>${escapeHTML(p.spiritRoot)}</h3><small>${escapeHTML(p.rootDesc)}</small><p>悟性 ${escapeHTML(p.stats.悟性)}　根骨 ${escapeHTML(p.stats.根骨)}　福缘 ${escapeHTML(p.stats.福缘)}<br>神识 ${escapeHTML(p.stats.神识)}　魅力 ${escapeHTML(p.stats.魅力)}</p></div><div class="xg-actions"><button>打坐吐纳</button><button>寻找落脚处</button><button>打听仇家消息</button><button>随意走走</button></div>`}
function showPrologue(){let root=pickRoot(),alloc=emptyAllocation();const el=document.getElementById('xg-onboard');el.classList.add('open');
 const paint=()=>{const used=STAT_NAMES.reduce((n,k)=>n+alloc[k],0),left=FREE_POINTS-used;document.getElementById('xg-roll').innerHTML=`<b>${root.name}</b><small>${rootDesc(root)}</small><div class="xg-points">剩余自由点 <strong>${left}</strong> / ${FREE_POINTS}</div><div class="xg-alloc">${STAT_NAMES.map(k=>`<div><span>${k}<small>最终 ${alloc[k]+(root.bonus[k]||0)}</small></span><button data-stat="${k}" data-d="-">−</button><b>${alloc[k]}</b><button data-stat="${k}" data-d="+">＋</button></div>`).join('')}</div><small>单项最多自由投入 ${STAT_CAP} 点；显示的最终值已包含灵根修正。</small>`;document.querySelectorAll('#xg-roll [data-stat]').forEach(btn=>btn.onclick=()=>{const k=btn.dataset.stat,usedNow=STAT_NAMES.reduce((n,x)=>n+alloc[x],0);if(btn.dataset.d==='+'&&alloc[k]<STAT_CAP&&usedNow<FREE_POINTS)alloc[k]++;if(btn.dataset.d==='-'&&alloc[k]>0)alloc[k]--;paint()})};paint();
 document.getElementById('xg-reroll').onclick=()=>{root=pickRoot();paint()};
 document.getElementById('xg-onboard-cancel').onclick=()=>{el.classList.remove('open');runAction(showSlots)};
 document.getElementById('xg-begin').onclick=()=>runAction(async()=>{const name=document.getElementById('xg-name').value.trim(),gender=document.getElementById('xg-gender').value,used=STAT_NAMES.reduce((n,k)=>n+alloc[k],0);if(!name)return document.getElementById('xg-name').focus();if(used!==FREE_POINTS)return alert('还有 '+(FREE_POINTS-used)+' 点属性没有分配。');const button=document.getElementById('xg-begin');if(button.disabled)return;button.disabled=true;document.getElementById('xg-onboard-cancel').disabled=true;try{const next=newSave(name,gender,root,alloc);await dbPut(next);currentSave=next;localStorage.setItem(LAST_SLOT_KEY,currentSlot);el.classList.remove('open');renderHome()}finally{button.disabled=false;document.getElementById('xg-onboard-cancel').disabled=false}})}
async function showSlots(){const sheet=document.getElementById('xg-slots');sheet.classList.add('open');const list=document.getElementById('xg-slot-list');list.innerHTML='';for(let i=0;i<5;i++){const slot=SLOTS[i],s=await dbGet(slot),row=document.createElement('div');row.className='xg-slot';row.innerHTML=s?`<div><b>存档 ${i+1} · ${escapeHTML(s.player.name)}</b><small>${escapeHTML(s.player.gender||'')}　${escapeHTML(s.player.spiritRoot)}　${escapeHTML(s.player.realm)}</small></div><div><button data-load>进入</button><button data-del>删除</button></div>`:`<div><b>存档 ${i+1}</b><small>空白命途</small></div><button data-new>新建</button>`;row.querySelector('[data-load]')?.addEventListener('click',async()=>{currentSlot=slot;currentSave=s;localStorage.setItem(LAST_SLOT_KEY,slot);sheet.classList.remove('open');renderHome()});row.querySelector('[data-new]')?.addEventListener('click',()=>{currentSlot=slot;currentSave=null;sheet.classList.remove('open');showPrologue()});row.querySelector('[data-del]')?.addEventListener('click',()=>runAction(async()=>{if(confirm('删除这个存档？此操作无法撤销。')){await dbDelete(slot);if(currentSlot===slot){currentSlot=null;currentSave=null;document.getElementById('xg-content').textContent='';localStorage.removeItem(LAST_SLOT_KEY)}await showSlots()}}));list.append(row)}}
async function loadGame(){const last=localStorage.getItem(LAST_SLOT_KEY);if(last){const s=await dbGet(last);if(s){currentSlot=last;currentSave=s;renderHome();return}}await showSlots()}
function mount(){if(document.getElementById('xg-fab'))return;const fab=document.createElement('button');fab.id='xg-fab';fab.type='button';fab.title='问我';fab.innerHTML='<span class="xg-moon-emoji" aria-hidden="true">🌙</span>';const panel=document.createElement('section');panel.id='xg-panel';panel.innerHTML=`<div class="xg-head"><div><b>问 我</b><small>一念成仙 · 一念为凡</small></div><button id="xg-head-moon" class="xg-head-moon" type="button" aria-label="关闭面板"><span aria-hidden="true">🌙</span></button><div class="xg-mountain"><i></i><i></i><i></i></div></div><main id="xg-content"></main><nav aria-label="游戏导航">${navButton('home','主页','',true)}${navButton('person','人物')}${navButton('bag','储物')}${navButton('map','地图')}${navButton('settings','设置','xg-settings')}</nav><div id="xg-settings-sheet"><div class="xg-setting-title">设置<button id="xg-settings-close">×</button></div><button id="xg-slots-btn">五世存档</button><button id="xg-save">保存当前存档</button><button id="xg-update">重新载入游戏<small>应用已经下载好的扩展更新</small></button><p>五个独立存档均保存在本机 IndexedDB。角色资质、灵根、性别、门派与事件标记会随档保存，供后续奇遇系统判定。</p></div><div id="xg-slots"><div class="xg-setting-title">选择命途<button id="xg-slots-close">×</button></div><div id="xg-slot-list"></div></div><div id="xg-onboard"><button id="xg-onboard-cancel" type="button">← 返回存档</button><div class="xg-prologue"><small>序 · 烬余</small><h2>山门已灭，故人无归。</h2><p>那一夜，火烧了整座山。师门上下无一幸免，唯有你从断崖下醒来。</p><p>你记得剑光，也记得仇人的衣纹。可如今的你连握剑的手都在发抖。</p><p>想报仇，先活下去。想活下去，便修行。</p><label>留下你的名字</label><input id="xg-name" maxlength="12" placeholder="输入姓名"><label>性别</label><select id="xg-gender"><option value="女" selected>女</option><option value="男">男</option><option value="不详">不详</option></select><div id="xg-roll"></div><button id="xg-reroll">重测灵根</button><button id="xg-begin">此身入道</button></div></div>`;document.body.append(fab,panel);
let moved=false,sx=0,sy=0,sl=0,st=0;const restorePosition=()=>{let saved;try{saved=JSON.parse(localStorage.getItem(POS_KEY)||'null')}catch{localStorage.removeItem(POS_KEY)}if(!saved)return;const pos=clampFabPosition(saved.left,saved.top,52,52,innerWidth,innerHeight);fab.style.left=pos.left+'px';fab.style.top=pos.top+'px';fab.style.right='auto';fab.style.transform='none'};restorePosition();window.addEventListener('resize',restorePosition);const start=e=>{moved=false;const p=e.touches?.[0]||e;sx=p.clientX;sy=p.clientY;const r=fab.getBoundingClientRect();sl=r.left;st=r.top},move=e=>{if(!sx&&!sy)return;const p=e.touches?.[0]||e,dx=p.clientX-sx,dy=p.clientY-sy;if(Math.abs(dx)+Math.abs(dy)>6)moved=true;if(!moved)return;e.preventDefault();fab.style.transform='none';fab.style.right='auto';fab.style.left=Math.max(4,Math.min(innerWidth-fab.offsetWidth-4,sl+dx))+'px';fab.style.top=Math.max(4,Math.min(innerHeight-fab.offsetHeight-4,st+dy))+'px'},end=()=>{if(moved){const r=fab.getBoundingClientRect(),left=r.left+r.width/2<innerWidth/2?8:innerWidth-r.width-8;fab.style.left=left+'px';localStorage.setItem(POS_KEY,JSON.stringify({left,top:r.top}))}sx=sy=0};fab.addEventListener('touchstart',start,{passive:true});fab.addEventListener('touchmove',move,{passive:false});fab.addEventListener('touchend',end);fab.addEventListener('pointerdown',start);window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);fab.onclick=()=>{if(!moved){panel.classList.add('open');fab.classList.add('hide');runAction(loadGame)}};
const collapse=()=>{panel.classList.remove('open');document.getElementById('xg-settings-sheet').classList.remove('open');document.getElementById('xg-slots').classList.remove('open');document.getElementById('xg-onboard').classList.remove('open');fab.classList.remove('hide')};document.getElementById('xg-head-moon').onclick=collapse;document.getElementById('xg-settings').onclick=()=>document.getElementById('xg-settings-sheet').classList.add('open');document.getElementById('xg-settings-close').onclick=()=>document.getElementById('xg-settings-sheet').classList.remove('open');document.getElementById('xg-slots-btn').onclick=()=>{document.getElementById('xg-settings-sheet').classList.remove('open');runAction(showSlots)};document.getElementById('xg-slots-close').onclick=()=>document.getElementById('xg-slots').classList.remove('open');document.getElementById('xg-save').onclick=()=>runAction(saveNow);document.getElementById('xg-update').onclick=()=>runAction(async()=>{await saveNow();location.reload()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
