import test from 'node:test';
import assert from 'node:assert/strict';
import {indexedDB} from 'fake-indexeddb';
import {migrateSave} from '../storage/migrations.js';
import {settleIdle,localDay,paddleWidth} from '../systems/cultivation.js';
import {addCultivation,QI_REQUIREMENTS} from '../data/realms.js';
import {purchase,addItem} from '../systems/inventory.js';
import {createPuzzle,countSolutions,startLearning,useHint,completeLearning,setMainTechnique} from '../systems/techniques.js';
import {hintAllowance} from '../data/techniques.js';
import {createActions} from '../core/actions.js';
import {writeSave,readSave,updateSave} from '../storage/saves.js';
import {createPractice,stepPractice} from '../systems/practice.js';
globalThis.indexedDB=indexedDB;
const day=new Date(2026,8,22).getTime(),minute=60000;
function save(slot='slot1'){return migrateSave({slot,version:3,player:{name:'测试',realm:'炼气一层',cultivation:0,sect:'无门无派',stats:{根骨:8,神识:5}},inventory:[],events:[],flags:{kept:true}},day)}
function main(s){s.techniques.mastered=['basic-qi-guide'];s.techniques.main='basic-qi-guide';return s}
test('old saves migrate once, keep progress and turn old gift into a manual',()=>{const s=save();s.version=3;s.learnedMethods=[{id:'basic-qi-guide'}];migrateSave(s,day);assert.equal(s.player.spiritStones,20);assert.equal(s.inventory.length,1);s.player.spiritStones=0;migrateSave(s,day+minute);assert.equal(s.player.spiritStones,0);assert.equal(s.inventory.length,1);assert(s.flags.kept)});
test('purchase complete starter set, repeated manuals stack and full bags do not spend',()=>{const s=save();purchase(s,'iron-sword');purchase(s,'cloth-robe');purchase(s,'qi-manual');assert.equal(s.player.spiritStones,0);assert.equal(s.inventory.length,3);s.player.spiritStones=20;s.bagCapacity=3;purchase(s,'qi-manual');assert.equal(s.inventory.find(item=>item.itemId==='qi-manual').quantity,2);assert.equal(s.player.spiritStones,10);assert.throws(()=>purchase(s,'iron-sword'));assert.equal(s.player.spiritStones,10)});
test('daily idle cap, idempotence and local-midnight reset',()=>{const s=main(save());assert.equal(settleIdle(s,day+180*minute),60);assert.equal(settleIdle(s,day+180*minute),0);assert.equal(s.idle.usedMs,120*minute);assert.equal(settleIdle(s,day+24*60*minute),0);assert.equal(s.idle.day,localDay(day+24*60*minute));assert.equal(s.idle.usedMs,0);assert.equal(settleIdle(s,day+25*60*minute),30)});
test('multiple offline dates each capped; no income without main or on clock rollback',()=>{const s=main(save());assert.equal(settleIdle(s,day+3*24*60*minute),180);assert.equal(s.player.realm,'炼气二层');assert.equal(s.player.cultivation,30);assert.equal(settleIdle(s,day),0);const other=save();assert.equal(settleIdle(other,day+60*minute),0);main(other);assert.equal(settleIdle(other,day+61*minute),.5)});
test('changing main first settles old rate, no retroactive accrual',()=>{const s=main(save());settleIdle(s,day+60*minute);setMainTechnique(s,null);assert.equal(settleIdle(s,day+120*minute),0);assert.equal(s.player.cultivation,30)});
test('4500 qi total, carry-over and cap at completion',()=>{assert.equal(QI_REQUIREMENTS.reduce((a,b)=>a+b),4500);const s=save();addCultivation(s,151);assert.equal(s.player.realm,'炼气二层');assert.equal(s.player.cultivation,1);addCultivation(s,10000);assert.equal(s.player.realm,'炼气圆满');assert.equal(s.player.cultivation,0);assert.equal(addCultivation(s,10),0)});
test('3/4/5 grids have unique solutions and exact hint thresholds',()=>{for(const size of [3,4,5])for(let i=0;i<8;i++){const puzzle=createPuzzle(size,10);assert.equal(countSolutions(puzzle.givens,size),1);assert(puzzle.givens.some(v=>v===0));assert.equal(countSolutions(puzzle.solution,size),1)}assert.deepEqual([4,5,9,10,20].map(hintAllowance),[0,1,1,2,2])});
test('learning persists hints, consumes manual only on success and requires equip',()=>{const s=save();addItem(s,'qi-manual');startLearning(s,'basic-qi-guide');useHint(s,'basic-qi-guide');assert.equal(startLearning(s,'basic-qi-guide').hintsUsed,1);assert.throws(()=>useHint(s,'basic-qi-guide'));assert.throws(()=>completeLearning(s,'basic-qi-guide'));const puzzle=s.techniques.puzzles['basic-qi-guide'];puzzle.cells=[...puzzle.solution];completeLearning(s,'basic-qi-guide');assert.equal(s.inventory.length,0);assert.equal(s.techniques.main,null);setMainTechnique(s,'basic-qi-guide');assert.throws(()=>completeLearning(s,'basic-qi-guide'))});
test('fixed physics detects a paddle hit and zero-root paddle remains playable',()=>{assert.equal(paddleWidth(0),30);assert.equal(paddleWidth(8),40);assert.equal(paddleWidth(100),100);const g=createPractice(8);g.launched=true;g.ball.x=g.paddle.x;g.ball.y=g.paddle.y-10;g.ball.vy=210;g.ball.vx=0;stepPractice(g,.04);assert(g.ball.vy<0)});
test('atomic saves prevent concurrent overspending and failed changes roll back',async()=>{await writeSave(save('concurrent'));await Promise.all(Array.from({length:5},()=>updateSave('concurrent',s=>{purchase(s,'iron-sword');return s}).catch(()=>null)));const s=await readSave('concurrent');assert.equal(s.player.spiritStones,0);assert.equal(s.inventory.length,4);await assert.rejects(updateSave('concurrent',s=>{s.player.spiritStones=999;throw new Error('stop')}));assert.equal((await readSave('concurrent')).player.spiritStones,0)});
test('practice reward is exactly-once and isolated per slot',async()=>{let current=save('practice');const api=createActions({getSave:()=>current,setSave:s=>current=s});await writeSave(current);const started=await api.startPractice();await api.finishPractice(started.result,25,'practice');assert.equal(current.player.cultivation,1);await assert.rejects(api.finishPractice(started.result,25,'practice'));assert.equal((await readSave('practice')).player.cultivation,1);current=main(save('another'));current.idle.lastAt=Date.now()+60000;await writeSave(current);const next=await api.startPractice();await api.finishPractice(next.result,25,'another');assert.equal(current.player.cultivation,50)});
