import {ITEMS,SHOP_ITEMS} from '../data/items.js';
import {sellExtra,discardJunk,purchase,equipItem,ownsTechnique,claimLoot,sellEquipment,discardEquipment,usePill,equipmentSalePrice,maxDurability,sellMaterial,MATERIAL_SALE_PRICE,sellPill,pillSalePrice} from '../systems/inventory.js';
import {createSheet,escapeHTML,format,buttonTask} from './shared.js';
import {techniqueLibrary} from './techniques.js';
export function renderInventory(api){
 const save=api.getSave();if(!save)return;api.activate('bag');
 const content=document.getElementById('xg-content');
 content.innerHTML=`<section class="xg-feature xg-bag"><div class="xg-bag-caption"><span>灵石 <b>${format(save.player.spiritStones)}</b></span><span>储物 ${save.inventory.length}/${save.bagCapacity}</span></div><div class="xg-bag-grid">${Array.from({length:Math.max(save.bagCapacity,save.inventory.length)},(_,i)=>{const entry=save.inventory[i],item=ITEMS[entry?.itemId];return entry?`<button type="button" data-item="${escapeHTML(entry.uid)}"><b>${escapeHTML(item?.glyph||'物')}</b><small>${escapeHTML(item?.name||entry.name||'旧物')}${entry.quantity>1?' ×'+entry.quantity:''}${entry.itemId==='crafted-binding-array'?(entry.usesLeft>0?' · '+entry.usesLeft+'/6':' · 损坏'):''}</small>${Object.values(save.equipment).includes(entry.uid)?'<em>已装备</em>':''}</button>`:'<div class="xg-bag-empty" aria-label="空储物格">·</div>'}).join('')}</div>${save.temporaryLoot?.length?`<div class="xg-temp-loot"><h3>临时储物 · 每批保留 30 分钟</h3>${save.temporaryLoot.map(entry=>`<button type="button" data-claim="${escapeHTML(entry.id)}">领取 ${escapeHTML(ITEMS[entry.itemId]?.name||'物品')} ×${entry.quantity} · 剩余 ${Math.max(0,Math.ceil((entry.expiresAt-Date.now())/60000))} 分钟</button>`).join('')}</div>`:''}<div class="xg-feature-row"><button type="button" data-expand>扩充储物</button></div><p class="xg-feature-message" role="status"></p></section>`;
 const message=content.querySelector('[role=status]');
 content.querySelector('[data-expand]').onclick=()=>message.textContent='扩容价格尚未确定，暂不扣除灵石。';
 content.querySelectorAll('[data-item]').forEach(button=>button.onclick=()=>showItem(api,button.dataset.item));
 content.querySelectorAll('[data-claim]').forEach(button=>button.onclick=()=>buttonTask(button,async()=>{await api.actions.mutate(s=>claimLoot(s,button.dataset.claim));renderInventory(api)},message));
}
export function showShop(api,gearOnly=false,onClose=()=>{api.closeFeature();renderInventory(api)}){
 const sheet=createSheet(gearOnly?'购买装备':'坊市商店',onClose),body=sheet.querySelector('[data-body]'),message=sheet.querySelector('[role=status]');
 const save=api.getSave();body.innerHTML=`<p>随身灵石：<b>${format(save.player.spiritStones)}</b></p>${SHOP_ITEMS.filter(id=>!gearOnly||ITEMS[id].kind==='equipment').map(id=>{const item=ITEMS[id],owned=item.kind==='manual'&&!item.repeatable&&ownsTechnique(save,item.methodId);return `<article class="xg-feature-card"><h3>${item.name}<small>${item.price} 灵石</small></h3><p>${item.description}</p><button type="button" data-buy="${id}" ${owned?'disabled':''}>${owned?'已拥有':'购买'}</button></article>`}).join('')}`;
 body.querySelectorAll('[data-buy]').forEach(button=>button.onclick=()=>buttonTask(button,async()=>{await api.actions.mutate(s=>purchase(s,button.dataset.buy),{message:result=>result});if(!sheet.isConnected)return;showShop(api,gearOnly,onClose);document.querySelector('#xg-feature-sheet [role=status]').textContent='已收入储物格。'},message));
}
export function showSell(api,onClose=()=>{api.closeFeature();renderInventory(api)}){
 const sheet=createSheet('出售物品',onClose),body=sheet.querySelector('[data-body]'),message=sheet.querySelector('[role=status]');
 const gear=api.getSave().inventory.filter(entry=>ITEMS[entry.itemId]?.kind==='equipment');
 const materials=api.getSave().inventory.filter(entry=>ITEMS[entry.itemId]?.kind==='material');
 const pills=api.getSave().inventory.filter(entry=>ITEMS[entry.itemId]?.kind==='pill');
 const extras=api.getSave().inventory.filter(entry=>Number.isFinite(ITEMS[entry.itemId]?.sellPrice));
 body.innerHTML=(gear.length?gear.map(entry=>{const item=ITEMS[entry.itemId],full=entry.durability===maxDurability(entry);return `<article class="xg-feature-card"><h3>${escapeHTML(item.name)}<small>耐久 ${format(entry.durability)} / ${maxDurability(entry)}</small></h3><p>${full?`满耐久可卖 ${equipmentSalePrice(item)} 灵石。`:'耐久未满，只能丢弃；修补费用待定。'}</p>${full?`<button type="button" data-sale="${escapeHTML(entry.uid)}">出售</button>`:''}<button type="button" data-discard="${escapeHTML(entry.uid)}">丢弃</button></article>`}).join(''):'')+materials.map(entry=>`<article class="xg-feature-card"><h3>${escapeHTML(ITEMS[entry.itemId].name)}<small>持有 ${entry.quantity}</small></h3><p>每份 ${format(MATERIAL_SALE_PRICE)} 灵石</p><button type="button" data-material="${escapeHTML(entry.uid)}">出售一份</button><button type="button" data-material-all="${escapeHTML(entry.uid)}">全部出售</button></article>`).join('')+pills.map(entry=>`<article class="xg-feature-card"><h3>${escapeHTML(ITEMS[entry.itemId].name)}<small>持有 ${entry.quantity||1}</small></h3><p>每枚 ${format(pillSalePrice(ITEMS[entry.itemId]))} 灵石</p><button type="button" data-pill="${escapeHTML(entry.uid)}">出售一枚</button><button type="button" data-pill-all="${escapeHTML(entry.uid)}">全部出售</button></article>`).join('')+extras.map(entry=>`<article class="xg-feature-card"><h3>${escapeHTML(ITEMS[entry.itemId].name)}<small>持有 ${entry.quantity||1}</small></h3><p>每份 ${ITEMS[entry.itemId].sellPrice} 灵石</p><button type="button" data-extra="${escapeHTML(entry.uid)}">出售一份</button></article>`).join('')||'<p>暂无可以出售的物品。</p>';
 body.querySelectorAll('[data-extra]').forEach(button=>button.onclick=()=>buttonTask(button,async()=>{await api.actions.mutate(s=>sellExtra(s,button.dataset.extra),{message:result=>result});if(sheet.isConnected)showSell(api,onClose)},message));
 body.querySelectorAll('[data-sale]').forEach(button=>button.onclick=()=>buttonTask(button,async()=>{await api.actions.mutate(s=>sellEquipment(s,button.dataset.sale),{message:result=>result});if(sheet.isConnected)showSell(api,onClose)},message));
 body.querySelectorAll('[data-discard]').forEach(button=>button.onclick=()=>buttonTask(button,async()=>{if(!confirm('丢弃这件装备？丢弃后无法找回。'))return;await api.actions.mutate(s=>discardEquipment(s,button.dataset.discard));if(sheet.isConnected)showSell(api,onClose)},message));
 body.querySelectorAll('[data-material],[data-material-all]').forEach(button=>button.onclick=()=>buttonTask(button,async()=>{const uid=button.dataset.material||button.dataset.materialAll,all=button.hasAttribute('data-material-all');await api.actions.mutate(s=>sellMaterial(s,uid,all?s.inventory.find(e=>e.uid===uid)?.quantity:1),{message:result=>result});if(sheet.isConnected)showSell(api,onClose)},message));
 body.querySelectorAll('[data-pill],[data-pill-all]').forEach(button=>button.onclick=()=>buttonTask(button,async()=>{const uid=button.dataset.pill||button.dataset.pillAll,all=button.hasAttribute('data-pill-all');await api.actions.mutate(s=>sellPill(s,uid,all?(s.inventory.find(e=>e.uid===uid)?.quantity||1):1),{message:result=>result});if(sheet.isConnected)showSell(api,onClose)},message));
}
function showItem(api,uid){
 const save=api.getSave(),entry=save.inventory.find(e=>e.uid===uid),item=ITEMS[entry?.itemId];if(!entry)return;
 const back=()=>{api.closeFeature();renderInventory(api)},sheet=createSheet(item?.name||entry.name||'旧物',back),body=sheet.querySelector('[data-body]'),message=sheet.querySelector('[role=status]');
 const stackPrice=item?.kind==='material'?MATERIAL_SALE_PRICE:item?.kind==='pill'?pillSalePrice(item):item?.sellPrice||0;
 const stackActions=stackPrice?`<button type="button" data-stack-sale>出售一份 · ${format(stackPrice)} 灵石</button>${(entry.quantity||1)>1?`<button type="button" data-stack-all>全部出售 · ${format((entry.quantity||1)*stackPrice)} 灵石</button>`:''}`:'';
 body.innerHTML=`<p>${escapeHTML(item?.description||'这件旧物已保留，暂不可使用。')}</p>${item?.kind==='equipment'?`<p>耐久 ${format(entry.durability)} / ${maxDurability(entry)}${entry.durability<=0?' · 已损坏，暂不能生效':''}</p>`:''}${entry.itemId==='crafted-binding-array'?`<p>${entry.usesLeft>0?`剩余 ${entry.usesLeft} / 6 次`:'损坏 · 无法在战斗中使用；以后可送礼，目前可以丢弃。'}</p>`:''}${item?.kind==='manual'?'<button type="button" data-use>阅读典籍</button>':item?.kind==='pill'?'<button type="button" data-use>服用</button>':item?.kind==='equipment'?`<button type="button" data-use>${Object.values(save.equipment).includes(uid)?'卸下装备':'装备'}</button>${entry.durability===maxDurability(entry)?`<button type="button" data-sale>出售 · ${format(equipmentSalePrice(item))} 灵石</button>`:''}<button type="button" data-discard>丢弃</button>`:''}${stackActions}${item?.kind==='junk'||entry.itemId==='crafted-binding-array'&&entry.usesLeft===0?'<button type="button" data-junk-discard>丢弃</button>':''}`;
 body.querySelector('[data-junk-discard]')?.addEventListener('click',e=>buttonTask(e.currentTarget,async()=>{await api.actions.mutate(s=>discardJunk(s,uid));if(sheet.isConnected)back()},message));
 const button=body.querySelector('[data-use]');if(button)button.onclick=()=>buttonTask(button,async()=>{if(item.kind==='manual'){techniqueLibrary(api,back);return}if(item.kind==='pill')await api.actions.mutate(s=>usePill(s,uid),{message:result=>result});else await api.actions.mutate(s=>equipItem(s,uid));if(sheet.isConnected)back()},message);
 body.querySelectorAll('[data-stack-sale],[data-stack-all]').forEach(button=>button.onclick=()=>buttonTask(button,async()=>{
  const all=button.hasAttribute('data-stack-all'),quantity=all?(api.getSave().inventory.find(e=>e.uid===uid)?.quantity||1):1;
  const {result}=await api.actions.mutate(s=>item.kind==='material'?sellMaterial(s,uid,quantity):item.kind==='pill'?sellPill(s,uid,quantity):sellExtra(s,uid,quantity),{message:result=>result});
  if(sheet.isConnected){back();document.querySelector('#xg-content [role=status]').textContent=result}
 },message));
 body.querySelector('[data-sale]')?.addEventListener('click',e=>buttonTask(e.currentTarget,async()=>{const {result}=await api.actions.mutate(s=>sellEquipment(s,uid),{message:result=>result});if(sheet.isConnected){back();document.querySelector('#xg-content [role=status]').textContent=result}},message));
 body.querySelector('[data-discard]')?.addEventListener('click',e=>buttonTask(e.currentTarget,async()=>{if(!confirm('丢弃这件装备？丢弃后无法找回。'))return;await api.actions.mutate(s=>discardEquipment(s,uid));if(sheet.isConnected)back()},message));
}
